name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  # -------------------------------------------------------------
  # Using GitHub's API
  # -------------------------------------------------------------
  # Event `pull_request`: Returns all changed pull request files.
  # --------------------------------------------------------------
  job1:
    # NOTE:
    # - This is limited to pull_request* events and would raise an error for other events.
    # - A maximum of 3000 files can be returned.
    # - For more flexibility and no limitations see "Using local .git directory" below.

    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    permissions:
      pull-requests: read

    steps:
      - name: Get changed files
        id: changed_files
        uses: tj-actions/changed-files@v37

      #- name: List all changed files
      #  run: |
      #    for file in ${{ steps.changed_files.outputs.all_changed_files }}; do
      #      echo "$file was changed"
      #    done
      
      - uses: actions/checkout@v1
      
      - name: test changes
        id: test-files
        run: |
          Write-Output "hier moechte ich checken"
          Write-Output $steps.changed_files.outputs.all_changed_files
          # Write-Output steps.changed_files.outputs.all_changed_files.GetType()

          foreach ( $file in $steps.changed_files.outputs.all_changed_files ) {
            # echo "$file was changed"
            if ($file -contains "azurepolicy.json") {
               Write-Host "$file was checked"
               .\Scripts\Confirm-PolicyDefinitionIsValid.ps1 $file
            }
          }
        shell: pwsh
